stages:
  - test
  - lint

variables:
  PYTHON_VERSION: "3.10"

before_script:
  - python --version
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install flake8 black pytest

test:
  stage: test
  image: python:${PYTHON_VERSION}
  script:
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
    - pytest tests/
  only:
    - main
    - merge_requests

black_check:
  stage: lint
  image: python:${PYTHON_VERSION}
  script:
    - black --check .
  only:
    - main
    - merge_requests

flake8_check:
  stage: lint
  image: python:${PYTHON_VERSION}
  script:
    - flake8 .
  only:
    - main
    - merge_requests
